---
name: Config-File
version: 1.53
author:
  - 'Gunnar Wolf <gwolf@gwolf.org>'
  - 'Sebastien J. Gross <seb@sjgross.org>'
  - 'Mikael Nordin <mikael.nordin@su.se>'
  - 'Johan Wassberg <jocar@su.se>'
abstract: Parse a simple configuration file
license: gpl
resources:
  bugtracker:
    web: https://github.com/stockholmuniversity/Config-File/issues
  license: http://opensource.org/licenses/gpl-license.php
  homepage: https://github.com/stockholmuniversity/Config-File
  repository:
    type: git
    url: https://github.com/stockholmuniversity/Config-File.git
    web: https://github.com/stockholmuniversity/Config-File

build_requires:
  Module::Build: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Config::File:
    file: lib/Config/File.pm
    version: 1.53
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
